<?php
$nps = array(
			"Código Cliente"=>1,
			"Del cero al diez, ¿Qué tanto recomendarías BACKUS a un amigo o conocido?"=>2,
			"¿Qué parte de la experiencia en BEES, recomendarías a otros? (Seleccione todas las que apliquen?)"=>array(
				"Productos BEES"=>array(
					"Productos BEES"=>"0-10",
					"Prefiero comprar productos a través de BEES sobre otros proveedores con los mismos productos."=>"9-10",
					"Solo compro productos a través de BEES si NO están disponibles a través de otros proveedores"=>"0-8",
					"El catálogo de productos BEES se alinea con mis necesidades comerciales"=>"9-10",
					"El catálogo de productos BEES NO es relevante para mis necesidades comerciales"=>"0-8",
					"Los precios en la aplicación BEES son competitivos."=>"9-10",
					"Los precios en la aplicación BEES NO son competitivos."=>"0-8",
					"Siempre hay suficiente inventario de los productos que quiero pedir."=>"9-10",
					"A menudo NO hay suficiente inventario de los productos que quiero pedir."=>"0-8"
				),
				"Proceso de ordenar a través de la aplicación BEES"=>array(
					"Proceso de pedido a través de la aplicación BEES"=>"0-10",
					"Aplicar Puntos a mi pedido es sencillo"=>"9-10",
					"Es difícil revisar mis puntos de recompensa y aplicarlos a mi pedido."=>"0-8",
					"La aplicación facilita ver los detalles de mi pedido o cancelar mi pedido si es necesario"=>"9-10",
					"NO puedo acceder fácilmente a información importante de la cuenta o actualizar mi pedido a través de la aplicación"=>"0-8",
					"Utilizo el módulo de pedidos sugeridos y me ahorra tiempo"=>"9-10",
					"El módulo Sugerir pedidos NO es útil para realizar mi pedido."=>"0-8",
					"Puedo realizar fácilmente mi pedido deseado a través de la aplicación BEES"=>"9-10",
					"Se necesita demasiado tiempo para realizar el pedido deseado."=>"0-8",
					"Estoy seguro de que recibiré el pedido exacto que realicé a través de la aplicación."=>"9-10",
					"No estoy seguro de que recibiré el pedido exacto que realicé a través de la aplicación."=>"0-8",
					"Es fácil encontrar nuevos productos que me interesan"=>"9-10",
					"Es difícil buscar nuevos productos que me puedan interesar"=>"0-8",
					"Las notificaciones de la aplicación BEES me mantienen actualizado sobre el estado de mi pedido y la entrega"=>"9-10",
					"Las notificaciones de la aplicación BEES sobre el estado del pedido y la entrega NO son útiles"=>"0-8"
				),
				"Promociones y Créditos (BEES)"=>array(
					"Promociones y crédito"=>"0-10",
					"Estoy satisfecho con los artículos disponibles para canjear."=>"9-10",
					"NO estoy satisfecho con los artículos disponibles para canjear"=>"0-8",
					"Entiendo cómo obtener beneficios de la empresa (Activaciones, sillas, mesas, congeladores)"=>"9-10",
					"NO sé cómo obtener beneficios de la empresa (Activaciones, sillas, mesas, hielera)"=>"0-8",
					"El programa Puntos es simple de entender y participar"=>"9-10",
					"Es difícil entender el valor del programa Puntos"=>"0-8",
					"Los desafíos de Puntos me ayudan a hacer crecer mi negocio"=>"9-10",
					"Los desafíos de Puntos NO me ayudan a hacer crecer mi negocio"=>"0-8",
					"El proceso para solicitar o aumentar mi crédito es fácil y transparente"=>"9-10",
					"El proceso para aumentar mi crédito no está claro o requiere mucho esfuerzo."=>"0-8",
					"Los requisitos que debo cumplir para aumentar mi límite de crédito tienen sentido para mi negocio"=>"9-10",
					"Los requisitos para aumentar mi límite de crédito NO tienen sentido para mi negocio"=>"0-8"
				),
				"Visitas de Vendedor (Asesor/BDR)"=>array(
					"Visitas de Vendedor (Asesor/BDR)"=>"0-10",
					"Necesito visitas de BDR ahora que puedo usar la aplicación BEES"=>"9-10",
					"Ya NO necesito visitas de BDR ahora que puedo usar la aplicación BEES"=>"0-8",
					"Mi BDR visita mi negocio con frecuencia"=>"9-10",
					"Mi BDR no visita mi negocio con la suficiente frecuencia"=>"0-8",
					"Mi BDR me brinda actualizaciones importantes sobre la funcionalidad de la aplicación BEES"=>"9-10",
					"Mi BDR NO me brinda actualizaciones importantes sobre la funcionalidad de la aplicación BEES"=>"0-8",
					"Mi BDR es consciente de mi tiempo cuando visitan mi negocio."=>"9-10",
					"Mi BDR es desconsiderado con mi tiempo cuando visitan mi negocio."=>"0-8",
					"Mi BDR me aconseja comprar productos que ayuden a hacer crecer mi negocio"=>"9-10",
					"Mi BDR impulsa productos que NO me ayudan a hacer crecer mi negocio"=>"0-8"			
				),
				"Experiencia de Entrega/Reparto (BEES)"=>array(
					"Experiencia de entrega"=>"0-10",
					"Mis entregas de BEES llegan el día que espero"=>"9-10",
					"Mis entregas de BEES a menudo se retrasan o se reprograman sin notificarme"=>"0-8",
					"Mis entregas de BEES tienen todos los productos que pedí"=>"9-10",
					"A mis entregas de BEES a menudo les faltan los productos que pedí"=>"0-8",
					"Los productos de mi pedido están en buenas condiciones para vender"=>"9-10",
					"Los productos de mi pedido a veces están dañados o caducados"=>"0-8",
					"El conductor de la entrega es profesional y servicial."=>"9-10",
					"El conductor de la entrega de BEES a veces es poco profesional o inútil"=>"0-8",
					"Cuando algo anda mal con mi entrega, los empleados de BEES me ayudan a corregir el problema."=>"9-10",
					"Cuando algo anda mal con mi entrega, me cuesta mucho esfuerzo corregir el problema."=>"0-8"			
				),
				"Interacción con el servicio al cliente (BEES)"=>array(
					"Interacción con el servicio al cliente"=>"0-10",
					"El servicio de atención al cliente me mantiene actualizado sobre el estado de mi solicitud si no pueden resolverlo de inmediato."=>"9-10",
					"NO sé el estado de mi solicitud cuando el Servicio de atención al cliente no puede resolverla de inmediato."=>"0-8",
					"Es fácil ponerse en contacto con el servicio de atención al cliente"=>"9-10",
					"Es difícil comunicarse con el servicio de atención al cliente."=>"0-8",
					"Es fácil ponerse en contacto con el Servicio de atención al cliente cuando necesito ayuda."=>"9-10",
					"Es dificil ponerse en contacto con el Servicio de atención al cliente cuando necesito ayuda."=>"0-8",
					"Los agentes de Atención al Cliente están informados sobre mi cuenta"=>"9-10",
					"Los agentes de servicio al cliente NO parecen saber mucho sobre mi cuenta"=>"0-8",
					"Los agentes de servicio al cliente pueden resolver cualquier problema que les plantee"=>"9-10",
					"Los agentes de servicio al cliente NO resuelven todos los problemas que les planteo"=>"0-8",
					"Los agentes de servicio al cliente manejan mis problemas con amabilidad."=>"9-10",
					"Los agentes de servicio al cliente NO tienen una actitud servicial"=>"0-8",
					"Siempre que solicito el mantenimiento del enfriador o un enfriador nuevo, recibo servicio y comunicación oportunos."=>"9-10",
					"Siempre que solicito el mantenimiento de un enfriador o un enfriador nuevo, NO recibo actualizaciones o servicio oportuno."=>"0-8",				
				),
		),"¿Tiene algún otro comentario que le gustaría hacer? ¿Cómo podemos mejorar su experiencia? Leemos todos los comentarios y valoramos su opinión. (Escriba el texto libre a continuación)"=>3
	);
?>