<?php
$centroAR = array (
				array("BK31","CD Ate","PE 01 - Lima + Norte Chico + Sur Chico"),
				array("BK34","CD Callao","PE 01 - Lima + Norte Chico + Sur Chico"),
				array("BK35","CD Cono","Norte	PE 01 - Lima + Norte Chico + Sur Chico"),
				array("BK36","CD Cono Sur","PE 01 - Lima + Norte Chico + Sur Chico"),
				array("BK37","CD Rímac","PE 01 - Lima + Norte Chico + Sur Chico"),
				array("BK38","CD Aguas Calientes","PE 03 - Centro Sur"),
				array("BK41","CD Ayacucho","PE 03 - Centro Sur"),
				array("BK43","CD Huancavelica","PE 03 - Centro Sur"),
				array("BK44","CD Ilo","PE 03 - Centro Sur"),
				array("BK46","CD Chiclayo","PE 02 – Norte Oriente"),
				array("BK47","CD Ancash","PE 02 – Norte Oriente"),
				array("BK48","CD Chimbote","PE 02 – Norte Oriente"),
				array("BK49","CD Trujillo","PE 02 – Norte Oriente"),
				array("BK50","CD Piura","PE 02 – Norte Oriente"),
				array("BK52","CD Talara","PE 02 – Norte Oriente"),
				array("BK53","CD Tumbes","PE 02 – Norte Oriente"),
				array("BK54","CD Motupe","PE 02 – Norte Oriente"),
				array("BK56","CD Cajamarca","PE 02 – Norte Oriente"),
				array("BK61","CD Cañete","PE 01 - Lima + Norte Chico + Sur Chico"),
				array("BK65","CD Vegueta","PE 01 - Lima + Norte Chico + Sur Chico"),
				array("BK66","CD Pto Maldonado","PE 03 - Centro Sur"),
				array("BK68","CD Huancayo","PE 03 - Centro Sur"),
				array("BK69","CD Ica","PE 01 - Lima + Norte Chico + Sur Chico"),
				array("BK76","CD Tacna","PE 03 - Centro Sur"),
				array("BK77","CD Juliaca","PE 03 - Centro Sur"),
				array("BK79","CD Arequipa","PE 03 - Centro Sur"),
				array("BK80","CD Cusco","PE 03 - Centro Sur"),
				array("SJ86","CD Satipo","PE 02 – Norte Oriente"),
				array("SJ87","CD Chanchamayo","PE 02 – Norte Oriente"),
				array("SJ90","CD Huánuco","PE 02 – Norte Oriente"),
				array("SJ91","CD Iquitos","PE 02 – Norte Oriente"),
				array("SJ93","CD Tingo María","PE 02 – Norte Oriente"),
				array("SJ94","CD Tarapoto","PE 02 – Norte Oriente"),
				array("SJ95","CD Yurimaguas","PE 02 – Norte Oriente"),
				array("SJ97","CD Pucallpa","PE 02 – Norte Oriente")
		);

?>